package com.example.register.persistence;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * repository which allows basic find/save/delete operations on database
 * implementation will be automatically generated by spring at runtime
 */
@Repository
public interface RegisterRepository extends JpaRepository<Register, String> {
}
